### ISSUE TITLE
Error Start Heroku

### ISSUE THREAD

**Issue by ghost** [Amalrajanj/filesaver#2]
Hello, sorry for the inconvenience, I get this error when mounting on Heroku.
could you help me? I think your bot is incredible. They would give me a contact to talk by telegram. 

![image](https://user-images.githubusercontent.com/31140793/116888923-62a7ac80-ac02-11eb-9d2a-62194adfac59.png)

**Comment by Amalrajanj** [comment]
t.me/Filestoringhelperbot

you can contact me here
